filter restricter fields
OpenSlides/openslides-search-service pull request #15
Opened 2023-04-06 10:54 UTC by bastianjoel

attempts to resolve #10
requires https://github.com/OpenSlides/openslides-autoupdate-service/pull/659

2023-04-06 13:16 UTC, bastianjoel commented on cmd/searchd/main.go
> +	}
This will be improved with #9

2023-04-06 13:50 UTC, s-l-teichmann requested changes

2023-04-06 13:50 UTC, s-l-teichmann commented on pkg/web/http.go
> +	fields *map[string][]string
I see no reason here to pass a pointer to the map. Maps are already reference types.

2023-04-11 11:00 UTC, s-l-teichmann approved these changes
LGTM

2023-04-11 11:00 UTC, s-l-teichmann commented on pkg/web/http.go
> +		requestedFields := make(map[string][]string, 0)
Drop the `0` or just write `requestedFields := map[string][]string{}`

2023-04-12 12:39 UTC, merged